server:
  port: 8080
zookeeper:
  server:
    list: 127.0.0.1:2181
  manage:
    spkeyInitPwd: 123456
    envAccKey: 123456
    sitpwd: 123456
    devpwd: 123456
    prepwd: 123456
    prodpwd: 123456
    adminPwd: cuber
spring:
  application:
    name: zookeeperManager
  thymeleaf:
    prefix: /templates/
    cache: false

zkprops:
  loader:
    location: file:/opt/pay/config.properties