server:
  port: 8080

zookeeper:
  server:
    list: 172.168.1.72:2181
  manage:
    mainpath: /zkconfig
    env: dev,sit,pre,prod
    encryptkeyPath: /zkconfig/encryptkey
    encryptNodeRegex: /zkconfig/encryptNodeRegex
    dev: 123456
    sit: 123456
    pre: 123456
    prod: 123456
spring:
  application:
    name: zookeeperManager
  thymeleaf:
    prefix: /templates/
    cache: false